# Generated by Django 3.0.8 on 2020-07-19 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_userrole_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='userForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
